name: industrial_ci

on: [push, pull_request]

jobs:
  industrial_ci:
    name: ROS ${{ matrix.ROS_DISTRO }} (${{ matrix.ROS_REPO }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ROS_DISTRO:
          - noetic
          - humble
          - iron
          - rolling
        ROS_REPO:
          - testing
          - main
    steps:
      - uses: actions/checkout@v3
      - uses: ros-industrial/industrial_ci@master
        with:
          config: ${{ toJSON(matrix) }}
